### ISSUE TITLE
Notification LED Force Close

### ISSUE THREAD

**Issue by VascoSousa1** [KcNirvana/MA-XML-9.0-PORTUGUESE#9]
When i go to settings»additional settings» Notifification LED it Force closes.

Ao escolher a opção Led de notificações em PT-PT dá force close.
Funciona normalmente em Inglês.
Xiaomi.eu 7.11.9
MI5s 4/128

**Comment by KcNirvana** [comment]
Boas...
Consegues postar aqui o FC?
Obrigado.

**Comment by VascoSousa1** [comment]
É isto?

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.util.IllegalFormatConversionException: e != java.lang.String
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.util.IllegalFormatConversionException: e != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4135)
	at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2845)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2792)
	at java.util.Formatter.format(Formatter.java:2497)
	at java.util.Formatter.format(Formatter.java:2426)
	at java.lang.String.format(String.java:2670)
	at android.content.res.Resources.getString(Resources.java)
	at com.android.settings.LedSettings.onCreate(LedSettings.java)
	at android.app.Fragment.performCreate(Fragment.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.BackStackRecord.setLastIn(BackStackRecord.java)
	at android.app.BackStackRecord.calculateFragments(BackStackRecord.java)
	at android.app.BackStackRecord.run(BackStackRecord.java)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java)
	at com.android.settings.H.aWA(SettingsActivity.java)
	at com.android.settings.H.onCreate(SettingsActivity.java)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	... 10 more

**Comment by VascoSousa1** [comment]
Só consigo aceder ao resumo quando tento aceder ao relatório ele simplesmente volta ao ecrã inicial.
